server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: userservice
  cloud:
    nacos:
      server-addr: localhost:8848
mybatis:
  type-aliases-package: com.tuling.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.tuling: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
